# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.C_dist_euclidean <- function(X) {
    .Call('dynnet_dist_euclidean', PACKAGE = 'dynnet', X)
}

.C_dist_euclidean2 <- function(X) {
    .Call('dynnet_dist_euclidean2', PACKAGE = 'dynnet', X)
}

norm_euclidean <- function(X) {
    .Call('dynnet_norm_euclidean', PACKAGE = 'dynnet', X)
}

distance_penalty <- function(X) {
    .Call('dynnet_distance_penalty', PACKAGE = 'dynnet', X)
}

.C_dmvnorm <- function(x, mean, sigma, logd = FALSE) {
    .Call('dynnet_dmvnorm', PACKAGE = 'dynnet', x, mean, sigma, logd)
}

.C_rmvnorm <- function(n, mu, sigma) {
    .Call('dynnet_rmvnorm', PACKAGE = 'dynnet', n, mu, sigma)
}

.C_llik_logit <- function(y, lp) {
    .Call('dynnet_C_llik_logit', PACKAGE = 'dynnet', y, lp)
}

.C_llik_poisson <- function(y, lp) {
    .Call('dynnet_C_llik_poisson', PACKAGE = 'dynnet', y, lp)
}

.C_lsm_MH <- function(y, X, Z_idx, k, d, burnin, samplesize, interval, beta, Z, family, dist_metric) {
    .Call('dynnet_C_lsm_MH', PACKAGE = 'dynnet', y, X, Z_idx, k, d, burnin, samplesize, interval, beta, Z, family, dist_metric)
}

.C_insert_ref <- function(ref_idx, ref_pos, est_idx, est_pos) {
    .Call('dynnet_insert_ref', PACKAGE = 'dynnet', ref_idx, ref_pos, est_idx, est_pos)
}

