# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.C_dmvnorm <- function(x, mean, sigma, logd = FALSE) {
    .Call('dynnet_C_dmvnorm', PACKAGE = 'dynnet', x, mean, sigma, logd)
}

.C_insert_ref <- function(ref_idx, ref_pos, est_idx, est_pos) {
    .Call('dynnet_C_insert_ref', PACKAGE = 'dynnet', ref_idx, ref_pos, est_idx, est_pos)
}

.C_dist_euclidean <- function(X) {
    .Call('dynnet_C_dist_euclidean', PACKAGE = 'dynnet', X)
}

norm_euclidean <- function(X) {
    .Call('dynnet_norm_euclidean', PACKAGE = 'dynnet', X)
}

distance_penalty <- function(X) {
    .Call('dynnet_distance_penalty', PACKAGE = 'dynnet', X)
}

C_llik_logit <- function(y, lp) {
    .Call('dynnet_C_llik_logit', PACKAGE = 'dynnet', y, lp)
}

C_llik_poisson <- function(y, lp) {
    .Call('dynnet_C_llik_poisson', PACKAGE = 'dynnet', y, lp)
}

.C_propose_Z <- function(Z) {
    .Call('dynnet_C_propose_Z', PACKAGE = 'dynnet', Z)
}

.C_propose_beta0 <- function(beta0) {
    .Call('dynnet_C_propose_beta0', PACKAGE = 'dynnet', beta0)
}

.C_log_prior_beta0 <- function(beta0) {
    .Call('dynnet_C_log_prior_beta0', PACKAGE = 'dynnet', beta0)
}

.C_log_prior_Z <- function(Z) {
    .Call('dynnet_C_log_prior_Z', PACKAGE = 'dynnet', Z)
}

.C_log_posterior_logit <- function(y, lp, beta0, Z) {
    .Call('dynnet_C_log_posterior_logit', PACKAGE = 'dynnet', y, lp, beta0, Z)
}

