# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llik_logit <- function(y, lp) {
    .Call('dynnet_llik_logit', PACKAGE = 'dynnet', y, lp)
}

llik_poisson <- function(y, lp) {
    .Call('dynnet_llik_poisson', PACKAGE = 'dynnet', y, lp)
}

norm_euclidean <- function(X) {
    .Call('dynnet_norm_euclidean', PACKAGE = 'dynnet', X)
}

distance_penalty <- function(X) {
    .Call('dynnet_distance_penalty', PACKAGE = 'dynnet', X)
}

